### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by michaelkuty** [jurismarches/luqum#25]
Hi, we have problem when we searching for license for this project we found License: GNU Lesser General Public License v3 or later (LGPLv3+) on https://pypi.org/project/luqum/ but in this repository we see GNU General Public License v3.0 

please which is correct ? however we recommend using LGPL because GPL is not suitable for most of companies

**Comment by alexgarel** [comment]
Hello @michaelkuty this is indeed LGPL. 
I will correct that very soon !

**Comment by michaelkuty** [comment]
Thanks !

**Comment by alexgarel** [comment]
Fixed.
