### ISSUE TITLE
Escape & invalid syntax

### ISSUE THREAD

**Issue by fabiopedrosa** [jurismarches/luqum#28]
I was under the impression luqum would be able to catch syntax issues, but is that not the case?

```python
test_query = '''http://crazy.c'"om OR a"teste"'''
tree = parser.parse('content: ({})'.format(test_query))
print str(tree)
es_builder = ElasticsearchQueryBuilder(not_analyzed_fields=["published", "tag"])
query = es_builder(tree)
print query
```

just prints:

```bash
content:(http\:\/\/crazy.c'"om OR a"teste")

{'bool': {'should': [{'match': {'content.http\\': {'query': '\\/\\/crazy.c\'"om', 'zero_terms_query': 'none'}}}, {'match': {'content': {'query': 'a"teste"', 'zero_terms_query': 'none'}}}]}}
```

which is not accepted syntax for ES.

**Comment by alexgarel** [comment]
Just a wrap up, looking more closely.

The first problem is the column after http, which makes http being interpreted like a field you want to search in. This is perfectly normal, and we can't correct that.

The second, is that we ignore single and double quotes if they are in the middle of an expression, this is maybe where we are too liberal.

However for now I close. You can eventually reopen @fabiopedrosa
