### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by fabiopedrosa** [jurismarches/luqum#29]
Unfortunately, we are stuck in Py2, and lurum is only compatible with Python. The only thing making it incompatible is the `yield from` usage, which is very very easy to convert into supported syntax. Would that be welcomed as a PR?

**Comment by alexgarel** [comment]
Yes I would welcome a PR if all tests passes (add the python 2.7 environment in travis.yml).

**Comment by alexgarel** [comment]
No PR at the moment, so I close it.

**Comment by alexgarel** [comment]
Note : if some one want to propose a PR, please discuss first, for this seems very late to add all the burden of Python2 compat, while Python2 is at the end of its life.
