### ISSUE TITLE
Support for "multi-fields" in ES transform

### ISSUE THREAD

**Issue by sefaYavuz** [jurismarches/luqum#33]
Just a question: Is the `keyword` datatype supported?

**Comment by alexgarel** [comment]
Yes it is supported.

Look at [ElasticsearchQueryBuilder](https://luqum.readthedocs.io/en/latest/api.html#luqum.elasticsearch.visitor.ElasticsearchQueryBuilder) there are options to specify the field that are not analyzed (that is are of type keywords).

Those parameters can be deduced from your mapping using [SchemaAnalyzer](https://luqum.readthedocs.io/en/latest/api.html#luqum.elasticsearch.schema.SchemaAnalyzer)

There is a short demonstration in [Quick Start](https://luqum.readthedocs.io/en/latest/quick_start.html#the-easy-way)

**Comment by sefaYavuz** [comment]
Thanks for your reply!

However I can't get it to work. With the following (partially) mapping for a single field:

```
"attributes":{
    "type":"nested",
    "properties":{
        "first_name":{
            "type":"text",
            "fields":{
                "raw":{
                    "type":"keyword"
                }
            }
        }
    }
}
```

As you can see I'm using a text field which is also a keyword. And fail in getting it working with the following search query: `attributes.first_name.raw:<search_query>`

**Comment by alexgarel** [comment]
Hum I don't think the schema analyzer support "fields" right now, nor the ElasticsearchQueryBuilder

This could be a good addition of course. I think it's like having an object_field, but relaxing a bit to enable calling it directly (and of course this as to be separate to be more understandable).

I may look into this, but I can't promise to have it quickly. If you are interested in making a PR it is welcome. I may guide you if you have questions after a first look at the code.

**Comment by alexgarel** [comment]
@sefaYavuz, if you use None for object_fields parameter of ElasticsearchQueryBuilder it should work !

**Comment by alexgarel** [comment]
@sefaYavuz I just pushed a commit fixing this problem.

You now have a sub_fields parameter on ElasticSearchQueryBuilder.

Could you test if it's ok on your side. If so, I would make a release.

**Comment by sefaYavuz** [comment]
@alexgarel Works as expected! When will you be able to make it into a release?

**Comment by alexgarel** [comment]
@sefaYavuz released : https://pypi.org/project/luqum/0.7.5/
