### ISSUE TITLE
Behavior of bare text in ElasticsearchQueryBuilder

### ISSUE THREAD

**Issue by seandavi** [jurismarches/luqum#35]
I have a pretty naive user community that likes simple plain-text search, but I also want to support power users with nested, field-based queries. When I have a query like:

```
cancer AND study.title:colon
```

The query translation after ElasticsearchQueryBuilder results in:

```
{"bool": {"must": [{"match": {"text": {"query": "cancer", "zero_terms_query": "all"}}}, {"match": {"study.title": {"query": "colon", "zero_terms_query": "all"}}}]}}
```

I'd like to simulate the behavior of the query_string with `cancer` to match against all available fields (not just a single field, as above). Is there a recommended configuration or approach that I can use to have the "best of both worlds" with nested and object query support while maintaining free text search for bare text? Sorry if I missed this in the docs.

**Comment by alexgarel** [comment]
'text' is the default field, you can change it using the default_field parameter of [ElasticsearchQueryBuilder](https://luqum.readthedocs.io/en/latest/api.html#luqum.elasticsearch.visitor.ElasticsearchQueryBuilder).

You could use `_all` for example : https://www.elastic.co/guide/en/elasticsearch/reference/6.2/mapping-fields.html#_indexing_meta_fields. Or you may have a text field indeed, that at indexation time, get content from all desired fields.

Another way you can do this is after parsing the query, you'll have [a tree](https://luqum.readthedocs.io/en/latest/api.html#module-luqum.tree). You may use the visitor pattern (or some other pattern) to transform the tree. Luqum [provides helpers](https://luqum.readthedocs.io/en/latest/api.html#module-luqum.utils) (caveats, they are still far from perfect).

the `cancer` part of the query should be represented by a `Word("cancer")`, that you may change to `OrOperation(SearchField("field1", Word("cancer")), SearchField("field2", Word("cancer")), …)`.

**Comment by seandavi** [comment]
Thanks, @alexgarel, for pointing me in the right direction. Luqum is crazy-nice to work with! Here is a stab at something that appears to work for me (edge cases to be found, yet, of course).

```
import luqum
from luqum.tree import SearchField, OrOperation, Word, Group

class BareTextTransformer(luqum.utils.LuceneTreeTransformer):
    """Convert bare Words to full text search

    In cases where a query string has bare text (no field
    association, we want to construct a DSL query that includes
    all fields in an OR configuration to perform the full
    text search against all fields. 

    This class can walk the tree and convert bare Word 
    nodes into the required set of SearchField objects.
    """
    def __init__(self, fields=['study.title', 'study.description', 'sample.title',
                               'sample.description']):
        """Create a new BareTextTransformer

        Parameters
        ----------
        fields: list of str
            This is the list of fields that will used to 
            create the composite SearchField objects that
            will be OR'ed together to simulate full text
            search.
        
        Returns
        -------
        None. The tree is modified in place.
        """
        super()
        self.fields = fields
    
    def visit_word(self, node, parent):
        if(len(parent)>0):
            if isinstance(parent[-1], luqum.tree.SearchField):
                return node
        else:
            search_list = [SearchField(f, node) for f in self.fields]
            return Group(OrOperation(*search_list))

>>> transformer = BareTextTransformer()
>>> new_tree = transformer.visit(tree)
```

I chose to put a `Group` around the `OrOperation` to avoid the AndOr on the same level error.
