### ISSUE TITLE
dual license?

### ISSUE THREAD

**Issue by feng-tao** [jurismarches/luqum#43]
We have a project which uses apache2 license. We would like to leverage this library but license is incompatible(https://apache.org/legal/resolved.html). Is it possible to do duel license for the project?

**Comment by alexgarel** [comment]
Hello @feng-tao, yes it is. Please, provide a PR, as I am travelling right now and do not have the time to do it carefully.

**Comment by feng-tao** [comment]
does https://github.com/jurismarches/luqum/pull/44 work? I couldn't find license header inside the code. Also not an expect on license side.

**Comment by alexgarel** [comment]
see e0920cbb0673ddf783846be6d410659a87047fce

**Comment by feng-tao** [comment]
thanks @alexgarel for the quick merge. Could we push a new pypi version which includes the new license? 

Exciting to adopt this library.

**Comment by alexgarel** [comment]
@feng-tao release done today !
