### ISSUE TITLE
Remove the SEPARATOR token?

### ISSUE THREAD

**Issue by Peter92** [jurismarches/luqum#47]
I don't know much about `yacc`, but I've been putting up with this warning each time I use `luqum` (I presume you already know it):

    WARNING: Token 'SEPARATOR' defined, but not used
    WARNING: There is 1 unused token

According to [this stackoverflow question](https://stackoverflow.com/questions/36707118/python-and-ply-how-to-get-rid-of-token-xxx-defined-but-not-used), the guy with a similar issue just removed the token from the list and it was fine.

Doing that fixed the warning for me, so I'm wondering if there's a particular reason you are keeping the `SEPARATOR` token? If it's genuinely not used, shouldn't it be removed from the source code?

**Comment by alexgarel** [comment]
Hi @Peter92 this is a good Idea. I may handle that later, but PR is always welcome :-)
