### ISSUE TITLE
missing elasticsearch-dsl dependency

### ISSUE THREAD

**Issue by Sonic0** [jurismarches/luqum#54]
Hi everyone,
In the latest version 0.9.0, I think there is a problem with the required dependency **elasticsearch-dsl**. Installing this package by pip, the compiler shows an error due to missing dependency. 
I think it's necessary to add in _requirement.txt_ and _setup.py_.

**Comment by impredicative** [comment]
Any update? Why do we really need this requirement? Can this requirement somehow be avoided? It would be better to avoid it than to list it. How did this even pass CI/tests?

**Comment by alexgarel** [comment]
elasticsearch-dsl is needed only for integration test. 

We should remove this. It is imported in `luqum/utils.py` but the use is in a test, so it really should be removed from there.

Hope to do this in the upcoming week.

**Comment by alexgarel** [comment]
Fixed by c80312ce9bbfd13bf96c2878a27dfdcaa10350c2
