### ISSUE TITLE
Allow forward slash in value of SearchField

### ISSUE THREAD

**Issue by impredicative** [jurismarches/luqum#58]
The forward slash character is currently not entirely allowed. It is dropped. I consider this character to be relevant in values of Search Fields. For a motivation, consider [GitHub code search by file location](https://docs.github.com/en/github/searching-for-information-on-github/searching-code#search-by-file-location) which uses it.

The query `foo bar:/baz` currently gets parsed as `foo bar:baz` which I think is incorrect.

**Comment by alexgarel** [comment]
Hi @impredicative, sorry but `bar:/` or `bar:/baz` is not a valid query according to ElasticSearch interpretation of LUCENE Query language.

If I try something like : `Book.search().filter("query_string", query="title:/").count()` using data defined in `test_es_integration`, I will get a:

```python
RequestError: RequestError(400, 'search_phase_execution_exception', 'Failed to parse query [title:/]')
```
The same stands for `title:/bar` `title:bar/baz` and so on…

Note that `/` is used to delimit regular expressions. `bar:/baz/` means searching the regexp "baz" if the field "bar".

Sorry but the line of luqum is to follow LUCENE query language syntax.
You could safely use `bar:"/baz" but I imagine you will find this not very satisfying…

Also PLY is based on LR-parsing, I'm not sure how well it would permits to use `/` to delimit regular expressions while also admitting it as terms.
