### ISSUE TITLE
Yacc warnings with ply 3.10

### ISSUE THREAD

**Issue by ahivert** [jurismarches/luqum#6]
We have these warning messages when we start the django shell with the 3.10 ply version
```
WARNING: yacc table file version is out of date
WARNING: Couldn't open 'parser.out'. [Errno 13] Permission non accordée: '/usr/local/lib/python3.4/dist-packages/luqum/parser.out'
WARNING: Token 'SEPARATOR' defined, but not used
WARNING: There is 1 unused token
Generating LALR tables
WARNING: 11 shift/reduce conflicts
WARNING: Couldn't create 'luqum.parsetab'. [Errno 13] Permission non accordée: '/usr/local/lib/python3.4/dist-packages/luqum/parsetab.py'
```

**Comment by ahivert** [comment]
e36b0fe

**Comment by alexgarel** [comment]
If you changed the PLY version you may need to regenerate parsetab.py (eg. by running the test) and commit it in the repository.

**Comment by alexgarel** [comment]
I have upgraded ply to version 3.10 in PR #13

**Comment by armisael** [comment]
@alexgarel can you elaborate on how to regenerate `parsetab.py` and commit it in the repository?

I'm using luqum 0.13.0 with ply 3.11 in a project where I just upgraded to python 3.13, and I'm getting the same warning:

```
WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/usr/local/lib/python3.13/site-packages/luqum/parser.out'
Generating LALR tables
WARNING: 2 shift/reduce conflicts
WARNING: Couldn't create 'luqum.parsetab'. [Errno 13] Permission denied: '/usr/local/lib/python3.13/site-packages/luqum/parsetab.py'
```

**Comment by alexgarel** [comment]
@armisael it seems you installed it system wide, so it is owned by root, thus you should use the parser at least once as root:

```bash
sudo python3
>>> from luqum.parser import parser
>>> parser.parse("test")
``` 
should be enough, I guess.
