### ISSUE TITLE
Support Surround Query Parser

### ISSUE THREAD

**Issue by urlence** [jurismarches/luqum#66]
https://lucene.apache.org/solr/guide/6_6/other-parsers.html#OtherParsers-SurroundQueryParser

Is Surround Query Parser not supported? 
like this:
`3w(foo, bar)` 
or
`(spot prices) 3w (gulf coast)`

**Comment by alexgarel** [comment]
Sorry it is not and it's not on the roadmap. 

It could be added but it should be in a sub package (to avoid confusion), with it's own package and additions to tree.py. Unfortunatley it's not easy with PLY to derive a parser from an existing one (it's still seems possible though, diving into PLY code to understand how to do it).

**Comment by hyun97** [comment]
Thanks for answer
Is there any way to convert surround query to lucene query?
Like this way
Surround Query -> Lucene Query -> Luqum -> ES query

**Comment by urlence** [comment]
Thank you for your answer.
Then I'd want to change the surround query to lucene query, do you know any way?
Like this way:
```
surround query -> lucene query -> luqum -> es query
```

**Comment by alexgarel** [comment]
@urlence : the parser build a tree (see tree.py).

If your tree is compatible, no problem to use luqum to [transform it to es query](https://luqum.readthedocs.io/en/latest/quick_start.html#transforming-to-elastic-query).

If your tree is not compatible, there are two ways:
* either you can [transform it](https://luqum.readthedocs.io/en/latest/quick_start.html#manipulating)
* either you'll have to extend the `ElasticsearchQueryBuilder` for your needs

Do'nt hesitate to dive in source or tests. If you have ideas of things we could document better, you are welcome !
