### ISSUE TITLE
Parser fails with 'TypeError' on invalid query "~]"

### ISSUE THREAD

**Issue by ygavenchuk** [jurismarches/luqum#69]
There's a query from pair of symbols which breaks the error handling of the parser, so we can't get relevant information about the syntax error.

**How to reproduce**:

```python
from luqum.parser import parser

parser.parse('~]')
```

**Expected result**: `ParseSyntaxError`
**Actual result**: `TypeError: __str__ returned non-string (type NoneType)`

**Possible fix**: 

Update the `TokenValue.__str__` [method](https://github.com/jurismarches/luqum/blob/master/luqum/head_tail.py#L21) to always return string. I.e.

```python
class TokenValue:
# ...
    def __str__(self):
        return str(self.value)
```

**Comment by alexgarel** [comment]
Hello @ygavenchuk, that's a good idea.

**Comment by ygavenchuk** [comment]
No problem

**Comment by delkopiso** [comment]
@alexgarel could you review https://github.com/jurismarches/luqum/pull/74?

**Comment by delkopiso** [comment]
@alexgarel will you be publishing a patch release for this fix?
