### ISSUE TITLE
Visitor example

### ISSUE THREAD

**Issue by thierrydecker** [jurismarches/luqum#77]
Is there any example of a tree visitor implmentation subclassing TreeVisitor base class ?

Can't find any example in the documentation.

My first use case is a visitor returning me a list of the search fields present in a tree.

**Comment by alexgarel** [comment]
see https://github.com/jurismarches/luqum/blob/master/tests/test_visitor.py where you can see basic examples like MROVisitor

**Comment by alexgarel** [comment]
@thierrydecker if you want to add an example to the documentation, you are really welcome. But for now I will close this issue.
