### ISSUE TITLE
Parse fails on word commas (eg "hi , bye")

### ISSUE THREAD

**Issue by cdrini** [jurismarches/luqum#79]
For example:

```py
from luqum.parser import parser
parser.parse('hi , bye')
# IllegalCharacterError: Illegal character ', bye' at position 3

parser.parse('hi, bye')
# UnknownOperation(Word('hi,'), Word('bye'))
```

Instead of an error, I expect to get:

```
UnknownOperation(Word('hi'), Word(','), Word('bye'))
```

**Comment by alexgarel** [comment]
@cdrini are you sure this is a valid Lucene query ?

**Comment by cdrini** [comment]
Hi @alexgarel ! Yep, I ran it in my solr instance and it treated it normally. Commas I don't believe are special characters anywhere in lucene; they shouldn't need escaping.

![image](https://user-images.githubusercontent.com/6251786/193166500-1da01785-9e6e-4b7f-ad9b-41be2cd91a2d.png)

**Comment by cdrini** [comment]
(Btw this package is fantastic! I recently started using it on https://github.com/internetarchive/openlibrary and it's made everything soooo much easier and enabled a whole new class of features that were simply to complicated before! Thank you so much! 😊)

**Comment by cdrini** [comment]
Woohoo, that was fast ! Awesome, thank you @alexgarel ! And @mmoriniere !
